version: '3.3'
services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - ./src:/usr/app/src
    ports:
      - 6969:6969
    environment:
      - CHOKIDAR_USEPOLLING=true
