version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/usr/src/app
    ports:
      - 9999:9999
    environment:
      - CHOKIDAR_USEPOLLING=true